# vim:syntax=zsh
# vim:filetype=zsh

#
# Executes commands at login before zshrc.
#
if [[ -z "$LANG" ]]; then
    export LANG='en_US.UTF-8'
    export LANGUAGE=en_US.UTF-8
fi

export LC_COLLATE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LESSCHARSET=utf-8

export EDITOR=nvim

export BRAZIL_COLORS=1
test -e "${HOME}/.mac-ca-roots" && export REQUESTS_CA_BUNDLE="$HOME/.mac-ca-roots"
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>/\\'

# eliminates duplicates in *paths
typeset -gU cdpath fpath path

# Zsh search path for executable
path=(
  /usr/local/{bin,sbin}
  /sbin/
  $path
)
